import Head from "next/head";
import Navbar from "../components/Navbar";

const Contact = () => {
  return (
    <>
      <Head>
        <title>Contact Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div>
        <Navbar />
        <div>
          Contact Page
          {/* {data?.username ? data.username : "User"} */}
        </div>
      </div>
    </>
  );
};

export default Contact;
