import axios from "axios";
import Head from "next/head";
import styled from "styled-components";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import nookies from "nookies";
import { NextApiRequest } from "next";
import { UserDetails } from "../types";

interface Props {
  activeUser: UserDetails[];
}

const Home = ({ details }: any) => {
  console.log(details);

  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Navbar />
      <div> {`Welcome ${details.firstName} ${details.lastName}!`}</div>
    </>
  );
};

export const getServerSideProps = async () => {
  let details = null;

  const { data } = await axios.get(
    "https://634cd1c5f5d2cc648e952d73.mockapi.io/users/1"
  );
  details = data;

  return {
    props: { details },
  };
};

export default Home;
