import axios from "axios";
import Head from "next/head";
import styled from "styled-components";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import nookies from "nookies";
import { NextApiRequest } from "next";

const Container = styled.div``;

interface Props {
  username: string;
  password: string;
  firstName: string;
  middleName: string;
  lastName: string;
  email: string;
  phone: string;
}

const Home = (props: Props) => {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div>
        <Navbar />
        <div>
          Welcome
          {props.firstName ? ` ${props.firstName}` : " Guest"}
        </div>
      </div>
    </>
  );
};

export const getServerSideProps = async () => {
  let user = null;

  try {
    const { data } = await axios.get(
      `https://634cd1c5f5d2cc648e952d73.mockapi.io/users/1`
    );

    user = data;
  } catch (e) {
    console.log(e);
  }

  return {
    props: user && user,
  };
};

// This gets called on every request
// export async function getServerSideProps() {
//   // Fetch data from external API
//   const res = await fetch(
//     "https://634cd1c5f5d2cc648e952d73.mockapi.io/users/1"
//   );
//   const data = await res.json();

//   // Pass data to the page via props
//   return { props: { data } };
// }

// export async function getServerSideProps() {
//   // Fetch data from external API
//   const res = await fetch("https://634cd1c5f5d2cc648e952d73.mockapi.io/users");
//   const data = await res.json();

//   // Pass data to the page via props
//   return { props: { data } };
// }

export default Home;
