import axios from "axios";
import Head from "next/head";
import styled from "styled-components";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import nookies from "nookies";
import { NextApiRequest } from "next";

interface Props {
  activeUser: {
    id: number;
    username: string;
    firstName: string;
    middleName: string;
    lastName: string;
    email: string;
    phone: string;
    isLogin: boolean;
  }[];
}

const Home = ({ activeUser }: Props) => {
  console.log(activeUser);

  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Navbar />
      {activeUser.map((user: any) => (
        <div key={user.id} className="capitalized">
          Welcome {`${user.firstName} ${user.lastName}`}!
        </div>
      ))}
    </>
  );
};

export const getServerSideProps = async (ctx: any) => {
  let activeUser = null;

  const { data } = await axios.get(
    "https://634cd1c5f5d2cc648e952d73.mockapi.io/users"
  );

  activeUser = data.filter((user: any) => {
    if (user.isLogin) {
      return user;
    }
  });

  return {
    props: { activeUser },
  };
};

export default Home;
